### ISSUE TITLE
getSmartMisfirePolicy does not exist - mentioned by MISFIRE_INSTRUCTION_SMART_POLICY

### ISSUE THREAD

**Issue by buzz3791** [quartz-scheduler/quartz#1122]
The documentation for org.quartz.Trigger#MISFIRE_INSTRUCTION_SMART_POLICY states "In order to see if this instruction fits your needs, you should look at the documentation for the getSmartMisfirePolicy() method on the particular Trigger implementation you are using."

But I can't find getSmartMisfirePolicy() defined on any Triggers or anywhere else in the source code.

**Comment by jhouserizer** [comment]
This must have already been fixed some time along the way, because the text currently reads "In order to see if this instruction fits your needs, you should look at the documentation for the <code>updateAfterMisfire()</code> method on the particular <code>Trigger</code> implementation you are using."

**Comment by jhouserizer** [comment]
I went ahead and added some javadoc links to that method of various core trigger types.
