### ISSUE TITLE
Update to tables_sqlServer.sql - IMAGE data type

### ISSUE THREAD

**Issue by begui** [quartz-scheduler/quartz#157]
It was brought to my attention that future version of sqlserver will be dropping support for the 'IMAGE' datatype

https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql

"ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use nvarchar(max), varchar(max), and varbinary(max) instead"

Are there any plans to update the sql script and replace the 'IMAGE' datatype?

**Comment by zemian** [comment]
Hello @Begui, thanks for bring this issue to our attention. Unfortunately I don't have a SQLServer to verify the changes needed. Would you be interested in contributing a tested script in a PR?

Much appreciate your help.
Thanks.

Zemian

**Comment by efwe** [comment]
Hello @zemian  and @begui,

we also noticed this. For completelness I'll add the messages produces by SQL server here.
``
Object dbo.QRTZ_BLOB_TRIGGERS.BLOB_DATA uses deprecated data type TEXT, IMAGE or NTEXT which will be discontinued for future versions of SQL Server. For more details, please see: Line 5, Column 5.

Object dbo.QRTZ_CALENDARS.CALENDAR uses deprecated data type TEXT, IMAGE or NTEXT which will be discontinued for future versions of SQL Server. For more details, please see: Line 4, Column 5.

 

Object dbo.QRTZ_JOB_DETAILS.JOB_DATA uses deprecated data type TEXT, IMAGE or NTEXT which will be discontinued for future versions of SQL Server. For more details, please see: Line 11, Column 5.

 

Object dbo.QRTZ_TRIGGERS.JOB_DATA uses deprecated data type TEXT, IMAGE or NTEXT which will be discontinued for future versions of SQL Server. For more details, please see: Line 17, Column 5.
``

So we have 4 places where the ``IMAGE`` type is used. Following the link to https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver15 i can see, that we may should update this to ``varbinary(max)``

I'll try to update https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore/tables_sqlServer.sql and test it locally.

I understood, that this is for new installations. How do you work with migrations for existing installations? Where should we place such a migration (if it could really work - i'm not sure how to migrate binary-columns).

Thanks a lot for all the good work,
Frank

**Comment by lahma** [comment]
You might want to check [how the .NET version script was updated to conform to new SQL Server versions](https://github.com/quartznet/quartznet/pull/787).  Please note that the column names and data types/sizes might differ a bit.

**Comment by efwe** [comment]
Hello @lahma ,
thanks for this pointer. The conditions look much better there and you also have the newer data-types of course. So do you support older SQL-Server also? Or did I read the MS documentation wrong. For how long is this ``varbinary(max)`` datatype around?

Actually I would prefer to concentrate on the data-types for now, would you prefer to update the conditional-syntax also? The create-statements themselves look identical already right?

The Java version also does not feature indexes for SQL Server while the Oracle create script has some.
This more looks like a 'global inconsistency' - I would not try to tackle that problem for now.

Kaizen,
Frank

**Comment by lahma** [comment]
@efwe I think `varbinary(max)` has been supported since SQL Server 2005. Generally I don't stress about supporting product versions that are End-Of-Life. [Here's current support listing](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=sql%20server&Filter=FilterNO) from where you can see that we are already past supporting even server version 2012. So especially with script like this meant to be run as part of new development, I wouldn't worry much about supporting these old versions.

Unfortunately as I've been outside of Java land for so long I can't commit to tweaking and testing a new script version, I'd rather see someone with better testing capabilities and use cases got about this.

**Comment by efwe** [comment]
Hi @lahma ,
thanks for all the good information. So this datatype is around 'forever' and I just completely misunderstood the following page https://docs.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-2014 
which brings that 'does not apply to the requested version' header.

2005 sounds OK - nobody should start a new project with an older database :) 
I'll prepare a minimal PR with only the datatype of the 4 blob columns changed.

hopeful,
Frank

**Comment by sahil-ag** [comment]
Hi @lahma 

I think @efwe 's PR looks fine and quite/exactly similar to how quartznet has done this..
* Removing [IMAGE Data Type](https://github.com/jvavasseur/quartznet/commit/37dff3e611242b6db26db61c0e94430afb5cd2b5#diff-f8409901036784f5b28419aeb3992b31)

Would it be possible to merge that PR if its good to go since we are planning to use Quartz Server with SQL Server 2019, and since its a new project, i dont want to use deprecated data types 🤔 

Thanks.
Sahil

**Comment by efwe** [comment]
Hello stale-bot :)

Sad enough this issue is still valid as the corresponding PR #515 has not yet landed. I will try to update it with tye `sign-off' message. 

Generally this is an issue worth to be fixed (given Quartz wants to support MSSQL further)

~fw
