### ISSUE TITLE
Release 2.2.3 - "getScheduledFireTime" + "DisallowConcurrentExecution"

### ISSUE THREAD

**Issue by usphisics** [quartz-scheduler/quartz#251]
I noticed that the "getScheduledFireTime" is returning the same value of "getFireTime" on a scenario that I don't allowed concurrency for the same job AND the job takes longer than the frequency interval that it was suppose to run.

Really simple way to simulate it:
* Create a Job Service, annotated it with "DisallowConcurrentExecution" and put it to run every 2min.
* Inside the Job Service class add a Thread.Sleep of 3min.

So here is what happens:
* Min 0 it will run normally
* Min 1 it wont run because we run every 2min --> 0 */2 * * * ? 
* Min 2 it wont run because the previous iteration didn't finish yet and we have "DisallowConcurrentExecution"
*Min 3 the first iteration job will finish AND immediately the one that didn't start on min 2 will start and here is moment that we want debug.
*** context.getFireTime() will return when the job was fired what is min 3, PERFECT, it is what we expects BUT if we do context.getScheduledFireTime() it will also return the same min 3 AND DOC IS CLEAR it was supposed to return the scheduled time that is min 2.

Observation:
* Just to know it was working in a old version but I don't remember which one, I had implemented the code at least 1 year ago and since then I already updated the quartz version few times but I just saw the issue today.
* Here is the way that today I init my quartz:
`
DirectSchedulerFactory.getInstance().createVolatileScheduler(10);
Scheduler scheduler = DirectSchedulerFactory.getInstance().getScheduler();
JobDetail job = JobBuilder.newJob(serviceExecutor).withIdentity(serviceExecutor.getName()).build();
Trigger trigger = TriggerBuilder.newTrigger().withSchedule(CronScheduleBuilder.cronSchedule(auxCron[0].trim())).build();					
scheduler.scheduleJob(job, trigger);
scheduler.start();
`

**Comment by jarlah** [comment]
this is definitely a problem. Would be great having this fixed, then i could compare firetime vs scheduledfiretime and eventually skip running the contents of the job ...

is this project maintained btw? last release was last year, and last commits on master (if we dont count terracotta) is from october last year?

**Comment by jarlah** [comment]
I have looked into the code. JobStoreSupport  line # 3007:

```
    protected TriggerFiredBundle triggerFired(Connection conn,
            OperableTrigger trigger)
        throws JobPersistenceException {

        // ....

        Date prevFireTime = trigger.getPreviousFireTime();

        // call triggered - to update the trigger's next-fire-time state...
        trigger.triggered(cal);

        // ....

       return new TriggerFiredBundle(job, trigger, cal, trigger.getKey().getGroup()
                .equals(Scheduler.DEFAULT_RECOVERY_GROUP), new Date(), trigger
                .getPreviousFireTime(), prevFireTime, trigger.getNextFireTime());
    }
```
inside trigger.triggered, for cron jobs:
```
    public void triggered(org.quartz.Calendar calendar) {
        previousFireTime = nextFireTime;
        nextFireTime = getFireTimeAfter(nextFireTime);

        while (nextFireTime != null && calendar != null
                && !calendar.isTimeIncluded(nextFireTime.getTime())) {
            nextFireTime = getFireTimeAfter(nextFireTime);
        }
    }
```
It seems to me that trigger.getScheduledFireTime() is equal to nextFireTime when the trigger was called. 

I cannot see technically that what you say is correct. To me fire time is new Date(), scheduledFiretime is nextFireTime and fireTime is the actual previous fire time.

Not sure if all of this is correct, but its not obvious whats wrong with the problem you describe.

PS. my two cents

**Comment by wrwatson** [comment]
We are also experiencing the same issue with a Cron schedule.

Our system uses `getScheduledFireTime()` to determine the date/time when the trigger should have logically run (if it didn't misfire).  The code then attempts to use this determine the date range on which it should be operating.  This means if triggers are missed due to an outage or other problem, when all the misfires trigger no time period will be missed.

I'm also unsure in which version this regressed because we don't have outages often.

At https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreSupport.java#L3102 the `TriggerFiredBundle` is created using `trigger.getPreviousFireTime()` as the `previousFireTime`. 

Perhaps the trigger implementation is setting `trigger.getPreviousFireTime()` to the actual fire time (i.e. now) rather then the scheduled fire time and then this is carried forward incorrectly.  Maybe this code should be taking `trigger.getNextFireTime()` at around line 3066 before `trigger.triggered(cal)` is called.

@zemian Are you aware of any work-around to determine when the trigger was scheduled to fire?
@usphisics Did you find any solution?

**Comment by usphisics** [comment]
No so far I still running over the issue. As you it isn't no often to
happen on my system to have missing running service so it isn't a big big
problem to me but yes it still to happen.

**Comment by wrwatson** [comment]
I've looked into this further and I think the underyling bug is at https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/impl/triggers/CronTriggerImpl.java#L628

This is the last line in the following snippet:

    public void updateAfterMisfire(org.quartz.Calendar cal) {
        int instr = getMisfireInstruction();

        if(instr == Trigger.MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY)
            return;

        if (instr == MISFIRE_INSTRUCTION_SMART_POLICY) {
            instr = MISFIRE_INSTRUCTION_FIRE_ONCE_NOW;
        }

        if (instr == MISFIRE_INSTRUCTION_DO_NOTHING) {
            Date newFireTime = getFireTimeAfter(new Date());
            while (newFireTime != null && cal != null
                    && !cal.isTimeIncluded(newFireTime.getTime())) {
                newFireTime = getFireTimeAfter(newFireTime);
            }
            setNextFireTime(newFireTime);
        } else if (instr == MISFIRE_INSTRUCTION_FIRE_ONCE_NOW) {
            setNextFireTime(new Date());
        }
    }

This is saying that the Cron trigger is _scheduled_ to fire at `new Date()` (i.e. now) and that is not the case since a misfire has happened.  I think if the misfire instruction is "fire once now" then the scheduled time should be either the first or last missed firing.  But also people actually using "fire once now" probably don't care terribly when it was meant to fire beacuse they likely have a job that catches up fully on one fire.

For my particular scenario, I want to use the misfire instruction of "ignore" (which means fire them all).  It's only hitting this code at all for me due to: https://github.com/quartz-scheduler/quartz/issues/505

So a potential workaround for this issue is to change the misfire strategy to "ignore" or "do nothing".
