### ISSUE TITLE
[discussion] Unused and/or unnecessary modules?

### ISSUE THREAD

**Issue by jarlah** [quartz-scheduler/quartz#278]
1. management-xxx? (i dont really know what this is all about, but they are not included in parent pom)
2. system-tests? (i understand there might be legit tests there, but they are not included in parent pom)
3. terracotta? (is this some helper classes for terracotta? if not, why are they in a package named terracotta? and why is it included in parent pom?)
4. checkstyle? (are we supressing checkstyle errors by making fake checkstyle config? i have actually run checkstyle on the project and it is NOT checkstyle compliant)

**Comment by zemian** [comment]
Items 1 - 3 are all related to terracotta + quartz integration. The terracotta provides large scale in memory store for quartz. Since terracotta is sponsoring the project, so they have added their work in the repository. I believe terracotta has a open source edition as well, so it kind of make sense back when the repository was hosted under Terracotta hosts as well. I personally have not worked with Terracotta part of Quartz, so I can't give too much inputs on the code itself.

All of these are optional add on to supplement Quartz. Not strictly needed I suppose. Removing it would make Quartz repo cleaner, but then that will be the repository owner to make. We can send a email to the DEV LIST for opinion and see.

As far as the checkstyle, I am sure it is not strictly enforce and specially there is not much development is going on, it's less important at this point. I think the modern IDE code formatter is decent enough that most code would come in decent shape. I would much like to see actual code contribution than picking on someone else style at this point.

**Comment by jarlah** [comment]
quartz module is only compability or upgradability tests for terracotta

**Comment by jarlah** [comment]
As for checkstyle no was not going to suggest any New code style. I was Just stating the obvious. There is no actual checkstyle config. :) thus can be removed. Look for your self

**Comment by zemian** [comment]
I will close this since there is a new task #292 to track these now. Maybe there are good candidate for 3.0.x or even 2.4.x branches.
