### ISSUE TITLE
Until you update to Java Jigsaw modules, please at least add "Automatic-Module-Name"

### ISSUE THREAD

**Issue by electrotype** [quartz-scheduler/quartz#405]
Until you migrate all your artifacts to use "module-info.java" properly, please at least properly name them by adding "`Automatic-Module-Name`" to their `MANIFEST.MF` file.

http://branchandbound.net/blog/java/2017/12/automatic-module-name/

You can easily do that using a Maven plugin. For example: https://maven.apache.org/shared/maven-archiver/examples/manifestEntries.html

**Comment by bsandiford** [comment]
Please do this.  Without it, javadoc generation is failing at a source = 11 level with maven-javadoc-plugin.  Without either a automatic-module-name in the manifest, or module-info.class at the root of the jar, the artifacts go into the --patch-module set rather than the --module-path set, and javadoc fails on unable to find referenced classes in the quartz jars.

**Comment by Sineaggi** [comment]
This issue is still relevant. Can we get it reopened?
