### ISSUE TITLE
Plans to release new version 2.3.1?

### ISSUE THREAD

**Issue by zhaowenxishi** [quartz-scheduler/quartz#406]

**Comment by zemian** [comment]
Hi, we don't have a release plan. The latest work on 2.3.x branch are track here: https://github.com/quartz-scheduler/quartz/blob/quartz-2.3.x/docs/changelog.adoc

For now, you can try to build it on your own. Tag it with the git commit hash to move on.

In order to perform officicial release, folks from Terracotta need to push the artifact into the Maven repo, which I do not have permission to do.

I can try to keep this issue open so other folks can vote and hopefully someone from Terracotta can help push it.

**Comment by PawelLipski** [comment]
@zemian I'd appreciate the release of a new version... to be honest I'm actually waiting for 2.4.0 (not 2.3.1 itself). Quartz 2.4.0 will bump HikariCP version to 3.2.0 (from current not 2.x) which also happens to be a transitive dependency of Play Framework 2.7.x (via play-slick 4.0.0). More details in the referencing issue https://github.com/enragedginger/akka-quartz-scheduler/issues/83.

**Comment by realmfoo** [comment]
Maybe @chrisdennis can help with it?

**Comment by zemian** [comment]
I have reached out to Terracotta folks and on the dev forum, but no reply yet. :(

At the mean time, for those of you who need a public release, I have tagged commit 70c94d38 as (quartz-2.3.1) and published in my own clone repository through JitPack. It is available here: https://jitpack.io/private#zemian/quartz/quartz-2.3.1

You can use it like this in Maven:

```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

...
	<dependency>
	    <groupId>com.github.zemian.quartz</groupId>
	    <artifactId>quartz</artifactId>
	    <version>quartz-2.3.1</version>
	</dependency>
```

Here is a full example should you need it: https://github.com/zemian/quartz-starter/tree/master/quartz-jitpack-quickstart

With out official release, that's the best I can do. I hope that helps!

**Comment by chrisdennis** [comment]
@zemian @realmfoo I'll chase this up tomorrow... sorry for being a slacker.

**Comment by chrisdennis** [comment]
New build has been tagged (v2.3.1). It should be up on Maven Central after the usual sonatype delays (it's usually within an hour if I recall correctly).  @zemian if you want to delete your quartz-2.3.1 tag to avoid confusion I guess that might be a good idea (although the two are basically identical).
