### ISSUE TITLE
Upgrade C3P0 to 0.9.5.4

### ISSUE THREAD

**Issue by zemian** [quartz-scheduler/quartz#419]

**Comment by jrbalsano** [comment]
Would it be possible to get a smaller point release (instead of 2.4.0) with this upgrade? There's a [CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5427) out for c3p0 that they've fixed in v0.9.5.4 ([release notes](https://github.com/swaldman/c3p0/blob/master/src/dist-static/RELEASE_NOTES-c3p0-0.9.5.4)).

**Comment by bdeining** [comment]
@zemian any update on whether we can put this on a minor release?

**Comment by Bdthomson** [comment]
@zemian Any updates?

**Comment by KokinSSJ** [comment]
[Any updates?](https://github.com/quartz-scheduler/quartz/issues/482#issuecomment-537825529)

**Comment by melloware** [comment]
@chrisdennis I think you can close this ticket since C3P0 has been updated.
