### ISSUE TITLE
error url

### ISSUE THREAD

**Issue by JackChan526** [quartz-scheduler/quartz#436]
https://github.com/quartz-scheduler/quartz/blob/master/docs/cookbook/CreateScheduler.html

**Comment by fioritonicolas** [comment]
Hey for that particular link the correct one is [http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/cookbook/CreateScheduler.html](url) 

It looks like you were navigating through the Documentation directly from GitHub repo that's why you get that link. I recommend seeing the documentation from the site [http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/cookbook/](url)
