### ISSUE TITLE
Cluster setup across TimeZones

### ISSUE THREAD

**Issue by harkinj** [quartz-scheduler/quartz#444]
Hi,
Great lib.
We are looking into the possibility of installing quartz in a cluster setup , across machines where some machines will be in US Hudson timezone and some in US Rochelle timezone ( we have non control over this).
I've noted "Never run clustering on separate machines, unless their clocks are synchronized using some form of time-sync service (daemon) that runs very regularly (the clocks must be within a second of each other)" in the docs and our machines will be time synced via internal ntp_servers.  Is our setup valid to support/use clustering?
Thanks for your time.
John

**Comment by Maegner** [comment]
@harkinj the way clustering works each instance will store it's own sytem timezone in the database when performing the hearth beat (check org.quartz,impl.jdbcjobstore.JobStoreSupport:3461) and also uses it's own timezone when verifying if any other node died. So if all your machines have the same time, this will work.
Otherwise it won't, at least until this is fixed.
