### ISSUE TITLE
404 links | Quartz Job Scheduler Tutorials

### ISSUE THREAD

**Issue by alanjeronimo** [quartz-scheduler/quartz#471]
https://github.com/quartz-scheduler/quartz/blob/master/docs/tutorials/index.adoc

**Comment by Guilai1990** [comment]
hi alanjeronimo, suppose Github fail to forward the link to correct resource.
Actually, you can find the resource with below link format like 
https://github.com/quartz-scheduler/quartz/blob/master/docs/tutorials/tutorial-lesson-01.md.
It looks like Github can not recognize the link https://github.com/quartz-scheduler/quartz/blob/master/docs/tutorials/tutorial-lesson-01.html.
And that's same for **Quartz Job Scheduler Cookbook**, you shall jump to https://github.com/quartz-scheduler/quartz/blob/master/docs/cookbook/BiDailyTrigger.md instead of https://github.com/quartz-scheduler/quartz/blob/master/docs/cookbook/BiDailyTrigger.html
