### ISSUE TITLE
Invalid misfired trigger breaks misfired trigger process

### ISSUE THREAD

**Issue by brianlenz** [quartz-scheduler/quartz#48]
We recently discovered a scenario where we had 20 perpetually misfired triggers in our Quartz scheduler. The jobs associated with these triggers were never being run, and it took a while to figure out why. It turns out there was an "invalid" misfired trigger that was "breaking" the misfire process. Specifically, a RECOVERING_JOBS trigger had a record in QRTZ_TRIGGERS with a TRIGGER_TYPE of 'SIMPLE', but there was _not_ a record in QRTZ_SIMPLE_TRIGGERS for it. As a result, each time the MisfireHandler ran, it would error out with an exception on the first trigger and skip the remaining 19 triggers.

```
08/10/16 12:41:06 [QuartzScheduler_ClusterScheduler-1470857567998_MisfireHandler] INFO  - Handling 20 trigger(s) that missed their scheduled fire-time.
08/10/16 12:41:06 [QuartzScheduler_ClusterScheduler-1470857567998_MisfireHandler] ERROR - MisfireHandler: Error handling misfires: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'RECOVERING_JOBS.recover_X.X.X.X1415014951113_1415015028210' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'ClusterScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
org.quartz.JobPersistenceException: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'RECOVERING_JOBS.recover_X.X.X.X1415014951113_1415015028210' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'ClusterScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1533)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:979)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3199)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3947)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3968)
Caused by: java.lang.IllegalStateException: No record found for selection of Trigger with key: 'RECOVERING_JOBS.recover_X.X.X.X1415014951113_1415015028210' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'ClusterScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
    at org.quartz.impl.jdbcjobstore.SimpleTriggerPersistenceDelegate.loadExtendedTriggerProperties(SimpleTriggerPersistenceDelegate.java:95)
    at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1819)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1531)
    ... 4 common frames omitted
```

It would be nice if there was some additional error handling to prevent against this scenario so that in the event one trigger has an issue, it doesn't prevent the other misfired triggers from being handled properly.

Note: of course, the secondary issue here is why the RECOVERING_JOBS trigger got into that invalid state in the first place, but I figure making the MisfireHandler more robust is a good place to start that would have prevented this issue for us.

**Comment by jhouserizer** [comment]
Additional error handling isn't a terrible idea, but isn't currently there because it would be checking for a situation that should never exist.  So really your "secondary issue" is actually the primary question.   I have been unable to reproduce or reason-through (analysis) how the situation could occur during the few sessions of time I have given this over the last few months.

Has this occurred to you more than once?  If so, please answer the following:

* which database
* which version of quartz
* configuration info regarding your connections (are you setting any particular isolation levels, etc.)
* full config (quartz.properties)

**Comment by brianlenz** [comment]
Sorry for the delayed response, @jhouserizer! We had the issue occur using:

* MySQL 5.6
* Quartz 2.2.2
* Transaction isolation level: READ_COMMITTED. `org.quartz.jobStore.lockOnInsert = false`
* We have our own `JobStoreSupport` implementation to handle connection acquisition and locking.

We are still using the same configuration as above, only we've upgraded to MySQL 5.7.

We've only seen the issue occur that one time, and it's not repeated itself again to my knowledge. I know this is surely an insufficient amount of information to be able to track down the issue with any certainty. We'll probably need to see it happen again and get more specific details.

I agree that the "secondary" issue is important here, but it still seems reasonable to me to do proper error handling when fetching triggers to avoid one bad trigger preventing others from being fired.

**Comment by cc4dogman** [comment]
Yes,I have a same problem! I try different combo api resolve then problem,but failed!
dont reschedule or delete And schedule job temp fix .... any one other solution??

**Comment by kbadruka** [comment]
We are also facing same issue. Below line is printed continuous in log file and application seems to hang (not processing further).
`
[2018-01-24 13:44:22] [ INFO] [_MisfireHandler] [] [o.s.s.quartz.LocalDataSourceJobStore    ][recoverMisfiredJobs      : 963] - Handling the first 20 triggers that missed their scheduled fire-time.  More misfired triggers remain to be processed.  `

Found one blog - https://www.ebayinc.com/stories/blogs/tech/performance-tuning-on-quartz-scheduler/ which says using batch mode will fix these issue. Can some one please confirm ?

**Comment by venkikeesara** [comment]
Hi 

We are also seeing the below message - 
2019-05-09 09:58:03,818 INFO  [org.springframework.scheduling.quartz.LocalDataSourceJobStore Thread:QuartzScheduler_schedulerFactory-NON_CLUSTERED_MisfireHandler] Handling the first 20 triggers that missed their scheduled fire-time.  More misfired triggers remain to be processed.

Also noticed more than 20 triggers are in mis fired state  using below query . ANy suggestion to process these misfired records 

SELECT * FROM QRTZ_TRIGGERS WHERE  ((TRIGGER_STATE = 'MISFIRED') OR (TRIGGER_STATE = 'WAITING')) ;-- and NEXT_FIRE_TIME < ?;

**Comment by Athen0212** [comment]
the same issue.
the method retrieveTrigger located at line 1532 in class JobStoreSupport.java will throwing an exception if there is a row of dirty data in the table qrtz_triggers. there is no corresponding data in the table QRTZ_SIMPLE_TRIGGERS or QRTZ_CRON_TRIGGERS.
but the invoker method recoverMisfiredJobs has not catch this exception. so foreach loop can not handle the rest of misfired jobs.
this issue will leading to all misfired jobs can not be handled.
the version of quartz is 2.3.0

**Comment by angest** [comment]
I got the same problem recently.

In my case, I found Quartz insert records to qrtz_triggers and qrtz_simple_triggers without using a transaction.  If there's exception after using qrtz_triggers then it will happen.
That's because I use Spring's SchedulerFactoryBean to control Quartz.  It calls Quartz's JobStoreSupport.setDontSetAutoCommitFalse(true) method.  So Quartz will use a connection with auto commit.
So I added @Transactional annotation to my service class (it wasn't there).  Now the inserting statements are in a transaction.

I couldn't reproduce the problem, so I can't say it can fix the problem.  I'll keep watching.  If the problem doesn't happen again, then probably it's the solution (for me).

**Comment by harshavardhan-upendram** [comment]
We are also getting the same issue.

We are getting below exception when the trigger entry is present in QRTZ_TRIGGERS but is missing in QRTZ_CRON_TRIGGERS table.
`MisfireHandler: Error handling misfires: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'DEFAULT.trigger-key' and statement: SELECT * FROM QRTZ_CRON_TRIGGERS WHERE SCHED_NAME = 'scheduler-name' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
`

This results in MisfireHandler not handling other misfires, till the DB entry is corrected for that one wrong trigger. MisfireHandler should handle other misfires in such cases.

**Comment by ryangraffy** [comment]
We have been able to reproduce this fairly reliably:
``` 
    IntStream.range(0, 500).forEach(num -> {
      var jobName = "JobName";
      var jobGroup = "JobGroup";
      var trigger = TriggerBuilder.newTrigger()
          .forJob(jobName, jobGroup)
          .withIdentity("test trigger #" + num)
          .build();
      var jobDetail = scheduler.getJobDetail(new JobKey(jobName, jobGroup));
      if (jobDetail != null) {
        return scheduler.scheduleJob(trigger);
      }
    });
```

**Comment by Eric-Hu-Windy** [comment]
I got the same error. My code:
```
trigger = TriggerBuilder.newTrigger().withIdentity(jobName, jobGroupName).withSchedule(
SimpleScheduleBuilder.repeatSecondlyForever(interval).withRepeatCount(repeatCount)
                    )
                    .startNow().build();
```
And I guess it's because scheduler retrieve simple trigger info from database before simple trigger data has persisted into database.
So I postpone the job for 3 seconds:
```
.startAt(DateUtils.addSeconds(new Date(), 3))
``` 
and increase database connection count:
```
druid:
      initialSize: 5
      minIdle: 10
      maxActive: 100
```
After that I don't get the error any more.

**Comment by howlettga** [comment]
@angest 
> That's because I use Spring's SchedulerFactoryBean to control Quartz. It calls Quartz's JobStoreSupport.setDontSetAutoCommitFalse(true) method. So Quartz will use a connection with auto commit.
> So I added @transactional annotation to my service class (it wasn't there). Now the inserting statements are in a transaction.

What service class did you annotate with @Transaction? Isn't the culprit here transactions done internally within the Quartz library or am I missing something? I am trying to figure out what is wrong with my Quartz TransactionManager configuration that it is not making these inserts through a transaction

**Comment by howlettga** [comment]
this is probably stale and closable, imo. In our case, transactions weren't actually the problem, as all our sql statements were running as transactions after-all. It was poor implementation where we manipulating jobs incorrectly. So if anyone else runs across this, I would say make sure you are fundamentally using good patterns in creating and removing jobs, and linking them. I could go check the commits where I fixed this to remember the situation that got us into this error state, but I assume it is not super common so no one needs it

**Comment by Whinight** [comment]
When we initiated multiple tasks within 1 second, a similar error occurred and the error log is as follows：

`ERROR [JobScheduler_QuartzSchedulerThread] org.quartz.core.ErrorLogger [QuartzScheduler.java:2407] - An error occurred while scanning for the next triggers to fire. 
org.quartz.JobPersistenceException: Couldn't acquire next trigger: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'XXXXX.921' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'JobScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.2.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) ~[quartz-2.3.2.jar:?]
Caused by: org.quartz.JobPersistenceException: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'XXXXX.921' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'JobScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1538) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2854) ~[quartz-2.3.2.jar:?]
	... 5 more
Caused by: java.lang.IllegalStateException: No record found for selection of Trigger with key: 'XXXXX.921' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'JobScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
	at org.quartz.impl.jdbcjobstore.SimpleTriggerPersistenceDelegate.loadExtendedTriggerProperties(SimpleTriggerPersistenceDelegate.java:110) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1819) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1536) ~[quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2854) ~[quartz-2.3.2.jar:?]
	... 5 more`

We had the issue occur using:

- Oracle
- Quartz 2.3.2
- quartz.properties：
  org.quartz.scheduler.rmi.export=false
  org.quartz.scheduler.rmi.proxy=false
  org.quartz.scheduler.wrapJobExecutionInUserTransaction=false
  org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
  org.quartz.jobStore.isClustered=true

If anyone could help with the answer, I would greatly appreciate it.

**Comment by jruivo-dev** [comment]
Also having the same issue, have any solutions been found?

**Comment by howlettga** [comment]
Our issue was the individual job threads were implemented in a way to manipulate job states or trigger new jobs themselves. This seemed like an anti-pattern, and examples show that the jobs themselves should simply return data or throw errors that then are handled by the main program making job decisions. When I removed job manipulation from the threads themselves and made all trigger and job scheduling come from the main classes' thread, trigger misfiring stopped. This may not be the only situation in which this type of error could occur, but for us, misfires were happening because the implementation led to the quartz state (quartz database tables) becoming invalid due to being manipulated by multiple threads that weren't intended to all manipulate the same state. So if an individual job thread manipulates a trigger, then the main thread later tries to access or manipulate the same trigger but it has already changed from what is expected, you would get misfires, or what happened for us was invalid states that would crash the quartz scheduler. 

That's why I don't think our individual code changes will help much. It is better to look at the example patterns suggested by quartz and implement your needs in a way that is mindful that the scheduler is multi-threaded yet stateful, so you need to be careful of how you could be manipulating state data that causes the different threads to become out of sync with the internal state of quartz.
