### ISSUE TITLE
quartz stopped by an OOM and is not recovered

### ISSUE THREAD

**Issue by dk020130** [quartz-scheduler/quartz#541]
Version: **2.3.1** (also exist in latest version);
Sometimes, our App got into OOM state for a short time due to a spike of request volume;
After memory issue is gone, everything is recovered to normal state except Quartz;
Because of OOM could results in QuartzSchedulerThread quit, thus Quartz stopped and never be recovered; we have to restart the server due to Quartz is broken;

the thread dump shows, there is 10 DefaultQuartzScheduler_Worker threads but no DefaultQuartzScheduler_**QuartzSchedulerThread** thread, and all worker threads are all same:
```
"DefaultQuartzScheduler_Worker-9" #31 prio=5 os_prio=0 tid=0x00007f49f61b6800 nid=0x28e5 in Object.wait() [0x00007f4993bfa000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000640be24c8> (a java.lang.Object)
```

Checked the code QuartzSchedulerThread.java, the "run" method only catches "RuntimeException", no "java.lang.Error'; so, OOM would lead to QuartzSchedulerThread quit;

Suggestions to handle this case by either:

1. Update QuartzSchedulerThread.run to catch "Error" and sleep for a while because of the app could be recovered from an "Error", QuartzSchedulerThread should be not stopped unless "shutdown" is invoked;
2. Update Quartz to provide a interface to restart QuartzSchedulerThread, so that we do not have to restart the whole server;

**Comment by jnehlmeier** [comment]
Catching any subclass of `VirtualMachineError`, which includes `OutOfMemoryError`, is a bad suggestion because there is no guarantee that the JVM / Thread is in a consistent state after the exception has been thrown by the JVM.

You should either
1. increase your heap
2. use more app servers to distribute workloads
3. implement your task in a less resource intensive manner

**Comment by dk020130** [comment]
we cannot ensure a app is not always running in a "good/healthy" state, just a few seconds of OOM that results in Quartz stopped, is it good?
if Quartz should not handle OOM, Quartz at least should provide a good interface to recover it (detect whether it is stopped and restart Quartz);
I prefer to Quartz should handle OOM;
the "shutdown" should be the only one way to stop Quartz;

**Comment by dk020130** [comment]
@jnehlmeier , 
> there is no guarantee that the JVM / Thread is in a consistent state after the exception has been thrown by the JVM

I agree with this, but it does not mean that "the JVM / Thread **MUST NOT** be in a consistent state after the exception has been thrown by the JVM".

JVM throws a "Error" instead of "System.exit(1)", it means JVM gives the system a chance to recover, and Quartz assumed the JVM/Thread must be broken, and killed this chance, it does not make sense;

After OOM, **Quartz can either keep working (preferably) or shutdown itself properly, but should not be broken** (isShutdown returns false and ThreadPool (10 workers) is still alive, but Quartz actually stopped);

**Comment by crHustler** [comment]
Hey @dk020130 @jnehlmeier 
I know its been long but any change you remember how were you able to solve this?
@jnehlmeier we are also experiencing this issue on a large scale 
Would really appreciate your insights on this

**Comment by jnehlmeier** [comment]
@crHustler I don't catch errors but instead let the JVM die so it will be restarted automatically by container orchestrator (docker / k8s). Other than that I do what I already mentioned. Basically adjust heap or quartz thread count or the implementation of the job.

**Comment by crHustler** [comment]
Thanks @jnehlmeier letting the jvm die would be a better approach since we don't know even if we catch the error, the jvm would recover completely or not
One question, is there a way to restart the QuartzSchedulerThread like not in case of OOME but in other cases where it was exited for instance, due to StackOverflowError due to a codepath which is not in our control?

**Comment by jnehlmeier** [comment]
> One question, is there a way to restart the QuartzSchedulerThread like not in case of OOME but in other cases where it was exited for instance, due to StackOverflowError due to a codepath which is not in our control?

The library does not expect `QuartzSchedulerThread` to terminate unexpectedly and if it does the library is in a broken state. You cannot recover from it. There is no API to restart the thread. So the best thing to do is to restart your application.

`QuartzSchedulerThread` already does catch all `RuntimeException` in its `run` method and logs them so only `Error` will terminate the thread. 
If `QuartzSchedulerThread` sees a `StackOverflowError` then it is a bug in the quartz library or any quartz extension/customization your application uses and it will not repair itself by trying to restart Quartz. You will quickly see the error again. It needs to be fixed.
If `QuartzSchedulerThread` sees an `OutOfMemoryError` then the thread was unlucky and required memory at a time the JVM cannot provide it or like `StackOverflowError` the library or any extension/customization has a bug and eats up all memory. Such a bug needs to be fixed as well.

So what can you do?

- You application should have some form of health checking so you know if all services your application has are healthy or not. Some services might be recoverable others might not. In case of Quartz being detected as unhealthy your application needs to restart.
  - You could write a thread watcher that checks if `QuartzSchedulerThread` is running or not
  - You could implement your own [Thread.UncaughtExceptionHandler](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.UncaughtExceptionHandler.html) and use it to detect if `QuartzSchedulerThread` is about to terminate

I don't know you application but if you really say that your `QuartzSchedulerThread` can die because of external code out of your control it seems you allow external code to extend Quartz. That is not a great situation to be in if you want a stable application. I would start thinking about refactoring the application and start treating Quartz as an implementation detail. That means your application needs its own job API and external partners have to programm against this new job API. The benefit is that you then have a small application layer between Quartz and the external code which allows you to react to exceptions and maybe even record misbehaving external code to block it until fixed.

**Comment by crHustler** [comment]
That clears it up
I was also thinking to add a threadWatcher that tracks the QuartzSchedulerThread and if it stops working, that implies that there is some problem with the jvm or the application server and thus, it is better to exit that app server from the cluster or restart it instead of restarting the QuartzScheduler thread on the same app server
Thanks a mil @jnehlmeier
