### ISSUE TITLE
Quartz Job fired twice in cluster mode

### ISSUE THREAD

**Issue by monalisha1994** [quartz-scheduler/quartz#731]
1- I am using spring-quartz version 2.3.6.RELEASE(Quartz version: 2.3.2). I am using MongoDB database to store my job details. 
2- My application is running in 4 node. Two node belongs to one region and another two node belongs to different region.
2- All triggers scheduled based on cron time.
2-In prod I am facing a lot of duplicate trigger run issue . but not able to replicate same in local.
3- I used @DisallowConcurrentExecution, still facing duplicate running of trigger.
4-I found org.quartz.jobStore.acquireTriggersWithinLock=true can resolve this issue, but this property is not supported by mongoDBJobStore.

Can someone give me any suggestion to resolve this issue.

Thank you in advance !!

**Comment by Dragas** [comment]
Yeah, use a real database.

**Comment by joaoportela** [comment]
@monalisha1994 I'm not an expert on quartz or mongodb, but:
 I know that in cluster mode, quartz depends a lot on the database isolation level guarantees, which is why for this kind of issues you see advice like "Check carefully about your cluster setting in scheduler config and your DB isolation level."

You should check if mongodb can provide the necessary isolation levels guarantees, otherwise, try a different database (like postgresql) for quartz.
