### ISSUE TITLE
Jobs not triggering on time

### ISSUE THREAD

**Issue by himanshusemwal3** [quartz-scheduler/quartz#883]
Hey, i have my spring batch application integrated with quartz scheduler. Somehow i have deleted data from batch_job_instance,batch_job_execution,batch_step_execution . After restart many of the jobs are working expected  with the cron expression timing. But some of the jobs are not getting triggered on time . When i checked batch_job_instance there is no job key generated .

I have also checked quartz_triggers tables.  I can see for my job prev_fire_time is -1 but next_fire_time keeps on changing  but its got never  triggerred . No job or job id is getting generated . Is there any way if i can trigger them manually from database query and resolve there next fire time automatically.

**Comment by jhouserizer** [comment]
Sorry, I don't know anything about the spring batch job stuff , nor how it utilizes quartz features.

It sounds from the symptoms you describe that the trigger is continuously misfiring, because misfire threshold is set way to low, or because there are not enough worker threads for how many jobs need to be running concurrently, or because the jobs are set up as non-concurrent-execution jobs, preventing others from running.
