### ISSUE TITLE
Quartz -Scheduler - how I edit configuration while scheduler is running?

### ISSUE THREAD

**Issue by danies8** [quartz-scheduler/quartz#899]
Hi, I have GUI client that insert configuration for the worker service using DB. The service read this configuration and run the job. I want to edit this configuration but the service is running. How I can update configuration while service is running ? Thanks in advance.

**Comment by jhouserizer** [comment]
I'm sorry, your wording and limited amount of information leave me unable to answer the question.  Maybe try re-stating your question and clarifying your setup.

**Comment by danies8** [comment]
@jhouserizer  
On server side , I have worker service that run many jobs using Quartz -Scheduler.
I have client that change the job details and triggers.
When I changed : Add/Edit/delete job details/triggers  i need that the Quartz -Scheduler will used this
"new configuation"
How is can be done?
Thanks in advance,

**Comment by danies8** [comment]
part of screens in client:
![image](https://github.com/quartz-scheduler/quartz/assets/1079689/f0af31e5-a79c-4be4-8134-e67f952e5a61)

**Comment by danies8** [comment]
worker service is the new name in .Net core for service

**Comment by danies8** [comment]
@jhouserizer
Can you please answer the question above ?

**Comment by jhouserizer** [comment]
Sorry, you may have more luck inquiring with the quartz .NET community,  as I / we here know very little about that.

But, to the extent that it is patterned after / transliterated from the original Java version of Quartz, the following is what I would recommend to someone using that:

* On the server side (where job should execute), instantiate and start a scheduler configured to use given db
* On the client side, instantiated, but do not start(), a scheduler configured to use the same given db.  Use that (initialized, but non-started) scheduler instance to retrieve/store/re-store  triggers and jobs
* The jobs will run on the server side because it's started there.

**Comment by danies8** [comment]
@jhouserizer Thanks for answer.
My problem is when jobs are running on server, and end user edit or add or remover job
how the server (the scheduler) can handle this **while is running** ?

**Comment by danies8** [comment]
end user edit or add or remover job con the client.
