### ISSUE TITLE
About org.quartz.jobStore.dontSetAutoCommitFalse

### ISSUE THREAD

**Issue by srgrr** [quartz-scheduler/quartz#950]
I have two questions about this boolean variable.

1) Why does the name contain a negation? It makes it hard to read
2) If setting it to true inevitably leads to undefined behavior issues as you state in your own docs why you're allowing users to change this value in the first place?
2.1) Why does Spring default to true if it leads to a behavior we explicitly want to avoid?

I would like to suggest to get rid of this value and rewrite whatever code it needs to be rewritten so it behaves as if it was implicitly set to false.

If this value needs to remain configurable I would like it to be renamed to setAutoCommitFalse or disableAutoCommit, or something that it's direct to read at least.

**Comment by jhouserizer** [comment]
1) the double-negative is because the code call setAutoCommit(false) , unless it is told not to.  It never calls setAutoCommit(true)  ... so it cant be called setAutoCommitTrue it has to be called dontSetAutoCommitFalse   because what the setting does is prevent the calling of setAutoCommit(false)
2) it's not a question of the USER doing something or not, it is a question of the default settings/behavior of the used database.
2.1) I can't answer for spring
